modLoader = "kotlinforforge"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/your-username/neoforge-telegram-bridge-bot/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "SERVER"
